
package yelp_gui;

import java.awt.BorderLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.ItemEvent;
import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JCheckBox;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import org.json.simple.parser.ParseException;

/**
 *
 * @author Malav
 */
public class Hw3 extends javax.swing.JFrame {

    /**
     * Creates new form YELP_GUI
     */
    public Hw3() {
        initComponents();
        populateBusCategory();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButtonExecuteQuery = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jDateChooserTo = new com.toedter.calendar.JDateChooser();
        jDateChooserFrom = new com.toedter.calendar.JDateChooser();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jComboBoxReviewStars = new javax.swing.JComboBox();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jTextFieldReviewStarsValue = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jComboBoxReviewVotes = new javax.swing.JComboBox();
        jLabel22 = new javax.swing.JLabel();
        jTextFieldReviewVotesValue = new javax.swing.JTextField();
        jPanel9 = new javax.swing.JPanel();
        jComboBoxCheckinFrom = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jComboBoxCheckinTo = new javax.swing.JComboBox();
        jTextFieldFrmCheckin = new javax.swing.JTextField();
        jTextFieldToCheckin = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jComboBoxNumOfCheckins = new javax.swing.JComboBox();
        jLabel25 = new javax.swing.JLabel();
        jTextFieldCheckinValue = new javax.swing.JTextField();
        jRadioButtonUser = new javax.swing.JRadioButton();
        jRadioButtonBusiness = new javax.swing.JRadioButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTextAreaQueryBuilder = new javax.swing.JTextArea();
        jPanelUser = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jDateChooserMemberSince = new com.toedter.calendar.JDateChooser();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jComboBoxReviewCount = new javax.swing.JComboBox();
        jComboBoxFriends = new javax.swing.JComboBox();
        jComboBoxAvgStars = new javax.swing.JComboBox();
        jComboBoxSelectCondition = new javax.swing.JComboBox();
        jTextFieldReviewCountValue = new javax.swing.JTextField();
        jTextFieldNoOfFriendsValue = new javax.swing.JTextField();
        jTextFieldAvgStarsValue = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButtoCatToSubCat = new java.awt.Button();
        jScrollPane6 = new javax.swing.JScrollPane();
        jPanelSubCategory = new javax.swing.JPanel();
        jScrollPane7 = new javax.swing.JScrollPane();
        jPanelBusCategory = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("YELP");
        setLocation(new java.awt.Point(0, 0));
        setResizable(false);
        setSize(new java.awt.Dimension(0, 0));

        jPanel4.setRequestFocusEnabled(false);
        jPanel4.setVerifyInputWhenFocusTarget(false);

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("RESULT");
        jLabel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(jTable2);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(246, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 557, Short.MAX_VALUE)
                .addContainerGap())
        );

        jScrollPane1.setViewportView(jPanel4);

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("CHECKIN");
        jLabel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("REVIEW");
        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jButtonExecuteQuery.setText("EXECUTE QUERY");
        jButtonExecuteQuery.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExecuteQueryActionPerformed(evt);
            }
        });

        jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jDateChooserTo.setDateFormatString("yyyy-MM-dd");

        jDateChooserFrom.setDateFormatString("yyyy-MM-dd");

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("from :");

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("to :");
        jLabel10.setToolTipText("");

        jComboBoxReviewStars.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "=, <, >", "=", "<", ">" }));

        jLabel19.setText("stars :");

        jLabel20.setText("value :");

        jLabel21.setText("votes :");

        jComboBoxReviewVotes.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "=, <, >", "=", "<", ">" }));

        jLabel22.setText("value :");

        jTextFieldReviewVotesValue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldReviewVotesValueActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel8Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel19))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel22)
                            .addComponent(jLabel21)
                            .addComponent(jLabel20)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel8Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(43, 43, 43)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jComboBoxReviewStars, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jDateChooserTo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextFieldReviewStarsValue, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jTextFieldReviewVotesValue, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBoxReviewVotes, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jDateChooserFrom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jDateChooserFrom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jDateChooserTo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(32, 32, 32)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxReviewStars, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(jTextFieldReviewStarsValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(jComboBoxReviewVotes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(jTextFieldReviewVotesValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(43, Short.MAX_VALUE))
        );

        jPanel9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jComboBoxCheckinFrom.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "No Selection", "SUNDAY", "MONDAY", "TUESDAY", "WEDNESDAY", "THURSDAY", "FRIDAY", "SATURDAY" }));

        jLabel1.setText("from :");

        jLabel23.setText("to :");

        jComboBoxCheckinTo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "No Selection", "SUNDAY", "MONDAY", "TUESDAY", "WEDNESDAY", "THURSDAY", "FRIDAY", "SATURDAY" }));

        jLabel24.setText("Num. of Checkins");

        jComboBoxNumOfCheckins.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "=,<, >", "=", "<", ">" }));

        jLabel25.setText("Value");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBoxCheckinFrom, javax.swing.GroupLayout.Alignment.TRAILING, 0, 91, Short.MAX_VALUE)
                    .addComponent(jComboBoxCheckinTo, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jComboBoxNumOfCheckins, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel23)
                            .addComponent(jLabel24)
                            .addComponent(jLabel1))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel25)
                    .addComponent(jTextFieldToCheckin, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextFieldCheckinValue, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextFieldFrmCheckin, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxCheckinFrom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldFrmCheckin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel23)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxCheckinTo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldToCheckin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(jLabel25))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxNumOfCheckins, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldCheckinValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(103, Short.MAX_VALUE))
        );

        jRadioButtonUser.setText("USER");
        jRadioButtonUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonUserActionPerformed(evt);
            }
        });

        jRadioButtonBusiness.setText("BUSINESS");

        jScrollPane5.setBorder(javax.swing.BorderFactory.createTitledBorder("QUERY BUILDER"));

        jTextAreaQueryBuilder.setColumns(20);
        jTextAreaQueryBuilder.setRows(5);
        jScrollPane5.setViewportView(jTextAreaQueryBuilder);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGap(0, 14, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jPanel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addComponent(jRadioButtonUser)
                        .addGap(46, 46, 46)
                        .addComponent(jRadioButtonBusiness)
                        .addGap(0, 105, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(111, 111, 111)
                .addComponent(jButtonExecuteQuery, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButtonUser)
                            .addComponent(jRadioButtonBusiness))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonExecuteQuery, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21))))
        );

        jPanelUser.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("USER");
        jLabel8.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel11.setText("Member since :");

        jLabel12.setText("Review Count :");

        jLabel13.setText("Num. Of Friends :");

        jLabel14.setText("Avg. Stars :");

        jLabel15.setText("Select :");

        jDateChooserMemberSince.setDateFormatString("YYYY-MM");
        jDateChooserMemberSince.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                jDateChooserMemberSinceInputMethodTextChanged(evt);
            }
        });

        jLabel16.setText("value :");

        jLabel17.setText("value :");

        jLabel18.setText("value :");

        jComboBoxReviewCount.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "=, <, >", "=", "<", ">" }));

        jComboBoxFriends.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "=, <, >", "=", "<", ">" }));

        jComboBoxAvgStars.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "=, <, >", "=", "<", ">" }));

        jComboBoxSelectCondition.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "AND, OR between attributes", "AND", "OR" }));

        jTextFieldReviewCountValue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldReviewCountValueActionPerformed(evt);
            }
        });

        jTextFieldAvgStarsValue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldAvgStarsValueActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelUserLayout = new javax.swing.GroupLayout(jPanelUser);
        jPanelUser.setLayout(jPanelUserLayout);
        jPanelUserLayout.setHorizontalGroup(
            jPanelUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelUserLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanelUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelUserLayout.createSequentialGroup()
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jComboBoxSelectCondition, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelUserLayout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(18, 18, 18)
                        .addComponent(jComboBoxReviewCount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel16)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldReviewCountValue, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelUserLayout.createSequentialGroup()
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jDateChooserMemberSince, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelUserLayout.createSequentialGroup()
                        .addGroup(jPanelUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(jLabel14))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelUserLayout.createSequentialGroup()
                                .addComponent(jComboBoxAvgStars, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel18)
                                .addGap(18, 18, 18)
                                .addComponent(jTextFieldAvgStarsValue, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelUserLayout.createSequentialGroup()
                                .addComponent(jComboBoxFriends, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel17)
                                .addGap(18, 18, 18)
                                .addComponent(jTextFieldNoOfFriendsValue, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(37, 113, Short.MAX_VALUE))
            .addGroup(jPanelUserLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelUserLayout.setVerticalGroup(
            jPanelUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelUserLayout.createSequentialGroup()
                .addComponent(jLabel8)
                .addGap(24, 24, 24)
                .addGroup(jPanelUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jDateChooserMemberSince, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanelUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jComboBoxReviewCount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16)
                    .addComponent(jTextFieldReviewCountValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jComboBoxFriends, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17)
                    .addComponent(jTextFieldNoOfFriendsValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxAvgStars, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18)
                    .addComponent(jTextFieldAvgStarsValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addGap(18, 18, 18)
                .addGroup(jPanelUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxSelectCondition, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addGap(92, 92, 92))
        );

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("BUSINESS");
        jLabel7.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("CATEGORY");
        jLabel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("SUB CATEGORY");
        jLabel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jButtoCatToSubCat.setLabel("GO");
        jButtoCatToSubCat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtoCatToSubCatActionPerformed(evt);
            }
        });

        jPanelSubCategory.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanelSubCategory.setLayout(new java.awt.GridLayout(0, 1));
        jScrollPane6.setViewportView(jPanelSubCategory);

        jPanelBusCategory.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanelBusCategory.setLayout(new java.awt.GridLayout(0, 1));
        jScrollPane7.setViewportView(jPanelBusCategory);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtoCatToSubCat, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addComponent(jButtoCatToSubCat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())))))
        );

        jScrollPane2.setViewportView(jPanel1);

        jScrollPane3.setViewportView(jScrollPane2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanelUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(52, 52, 52))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 436, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanelUser, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 15, Short.MAX_VALUE))
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldReviewCountValueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldReviewCountValueActionPerformed
        // TODO add your handling code here:
       // System.out.println(jTextFieldReviewCountValue.getText
        //jLabelQueryBuilder.setText(jTextFieldReviewCountValue.getText());
    }//GEN-LAST:event_jTextFieldReviewCountValueActionPerformed

    private void jTextFieldAvgStarsValueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldAvgStarsValueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldAvgStarsValueActionPerformed

    private void jTextFieldReviewVotesValueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldReviewVotesValueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldReviewVotesValueActionPerformed

    private void jDateChooserMemberSinceInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_jDateChooserMemberSinceInputMethodTextChanged
        // TODO add your handling code here:
         memberSince = jDateChooserMemberSince.getDateFormatString();
    }//GEN-LAST:event_jDateChooserMemberSinceInputMethodTextChanged

    private void jButtonExecuteQueryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExecuteQueryActionPerformed
        
       
        if(jRadioButtonUser.isSelected()){
            //JOptionPane.showMessageDialog(new JFrame(),"USER");
           
             String createUser = createUserQuery();
             displayResultTable(createUser);
             jRadioButtonUser.setSelected(false);
        }
        else if(jRadioButtonBusiness.isSelected()){
            
            String createBusiness = createBusinessQuery();
            displayResultTable(createBusiness);
           
            jRadioButtonBusiness.setSelected(false);
            
        }
        else
            JOptionPane.showMessageDialog(new JFrame(),"SELECT BUSINESS OR USER."); 
    
        
    }//GEN-LAST:event_jButtonExecuteQueryActionPerformed

    
    private String createBusinessQuery(){
        //Inputs from Review
        String from_date = (new SimpleDateFormat("yyyy-MM-dd")).format(jDateChooserFrom.getDate());
        String to_date = (new SimpleDateFormat("yyyy-MM-dd")).format(jDateChooserTo.getDate());  
        String stars_value=jComboBoxReviewStars.getSelectedItem().toString();
        int star=Integer.parseInt(jTextFieldReviewStarsValue.getText());
        String votes_value=jComboBoxReviewVotes.getSelectedItem().toString();
        int votes=Integer.parseInt(jTextFieldReviewVotesValue.getText());
        
        //Inputs from Checkin
         String fromday=jComboBoxCheckinFrom.getSelectedItem().toString();
          int fromdayValue=Integer.parseInt(jTextFieldFrmCheckin.getText());
          String today=jComboBoxCheckinTo.getSelectedItem().toString();
          int todayValue=Integer.parseInt(jTextFieldToCheckin.getText());
        
        String checkin=jComboBoxNumOfCheckins.getSelectedItem().toString();
        int checkin_value=Integer.parseInt(jTextFieldCheckinValue.getText());
        
        //Inputs from Business
        //Categories
        String busCatQuery = new String();
        for(int i=0;i<busCatSelected.length;i++){
           if(busCatSelected[i]!=null)
           busCatQuery +="'"+busCatSelected[i]+"',";
        }
         busCatQuery = busCatQuery.substring(0, busCatQuery.length()-1);
         
         
        //Sub-Categories
         //subCatSelected = new String[500];
        // int count = 0;
        for(int i=1;i<subCatSelected.length;i++){
            if(jCheckBoxSubCategory[i].isSelected()){
               subCatSelected[i] = jCheckBoxSubCategory[i].getText();
               //count++;
            }  
        }
         
         String subCatQuery = new String();
        for(int i=0;i<subCatSelected.length;i++){
           if(subCatSelected[i]!=null)
           subCatQuery +="'"+subCatSelected[i]+"',";
        }
         subCatQuery = subCatQuery.substring(0, subCatQuery.length()-1);
         //subCatQuery += "bleh";
         
         /*String subCatQuery = new String();
         for(int i=0;i<jCheckBoxSubCategory.length;i++){
             if(jCheckBoxSubCategory[i+1].isSelected()==true){
                 subCatQuery +="'"+jCheckBoxSubCategory[i+1].getText()+"',";
             }
         }*/
         
         /*String createBusiness = "SELECT * FROM YELP_BUSINESS B WHERE B.BUSINESS_ID IN "+
"((SELECT DISTINCT(BUSINESS_ID) FROM YELP_CHECKIN WHERE BUSINESS_ID IN"+
"((SELECT DISTINCT(BUSINESS_ID)  FROM YELP_CHECKIN WHERE DAY BETWEEN"+
"(SELECT DISTINCT(DAY) FROM YELP_CHECKIN WHERE MAP_DAYS(DAY) = '"+fromday+"') AND"+ 
"(SELECT DISTINCT(DAY) FROM YELP_CHECKIN WHERE MAP_DAYS(DAY) ='"+today+"'))"+ 
" INTERSECT"+
"(SELECT DISTINCT(BUSINESS_ID)  FROM YELP_CHECKIN WHERE HOUR BETWEEN "+fromdayValue+" AND "+todayValue+"))"+
" GROUP BY BUSINESS_ID"+
" HAVING SUM(CHECKINS)"+checkin+checkin_value+")"+
" INTERSECT"+
"(SELECT DISTINCT(R.BUSINESS_ID)"+
" FROM YELP_REVIEW R"+ 
" WHERE R.REVIEW_DATE BETWEEN '"+from_date+"' AND '"+to_date+"'"+ 
      "AND R.STARS"+stars_value+star+" "+
      "AND CAL_VOTES(R.USEFUL,R.FUNNY,R.COOL)"+votes_value+votes+")"+
" INTERSECT"+
"(SELECT DISTINCT(BC.BUSINESS_ID)"+ 
" FROM BUSINESS_CATEGORY BC"+ 
" WHERE BC.BUSINESS_CATEGORY = ANY("+busCatQuery+") "+
" AND BC.BUS_SUBCATEGORY = ANY("+subCatQuery+")))";*/
         
         String createBusiness = "SELECT *  FROM YELP_BUSINESS B"+ 
" WHERE B.BUSINESS_ID IN "+
"((SELECT BUSINESS_ID FROM"+ 
"((SELECT *  FROM YELP_CHECKIN WHERE MAP_DAYS(DAY)>'"+fromday+"' AND MAP_DAYS(DAY)<'"+today+"') "+
"UNION "+
"(SELECT * FROM YELP_CHECKIN  WHERE MAP_DAYS(DAY)='"+fromday+"' AND HOUR >= "+fromdayValue+")"+ 
 "UNION "+
"(SELECT * FROM YELP_CHECKIN WHERE MAP_DAYS(DAY)='"+today+"' AND HOUR <= "+todayValue+"))"+ 
"GROUP BY BUSINESS_ID "+
"HAVING SUM(CHECKINS)"+checkin+checkin_value+")"+ 
"INTERSECT "+
"(SELECT B.BUSINESS_ID FROM YELP_BUSINESS B,YELP_REVIEW R, BUSINESS_CATEGORY BC "+
" WHERE B.BUSINESS_ID = R.BUSINESS_ID "+
" AND R.BUSINESS_ID = BC.BUSINESS_ID "+
" AND  BC.BUSINESS_CATEGORY = ANY ("+busCatQuery+")"+  
" AND  BC.BUS_SUBCATEGORY = ANY ("+subCatQuery+")"+ 
" AND  R.STARS "+stars_value+star+" "+ 
" AND  CAL_VOTES(R.USEFUL,R.FUNNY,R.COOL) "+votes_value+votes+" "+
" AND  R.REVIEW_DATE BETWEEN '"+from_date+"' AND '"+to_date+"'))";
        
        return createBusiness;
    }
    
    private void populateSubCategory(String[] busCatSelected){
        String[] tempBusCatSelected = busCatSelected;
        //subCatSelected = new String[500];
        String createSubCatQuery = "Select distinct(BUS_SUBCATEGORY) from BUSINESS_CATEGORY where";
        for(int i=0;i<tempBusCatSelected.length;i++){
            if(tempBusCatSelected[i]!=null)
            createSubCatQuery += " BUSINESS_CATEGORY = '"+tempBusCatSelected[i]+"' OR";   
        }
        createSubCatQuery = createSubCatQuery.substring(0,createSubCatQuery.length()-3);
        dbConnect = new Connecting_DB();
            try {
                Connection con = dbConnect.openConnection();
                 Statement st = con.createStatement();
                // pst.setString(1, user_id);
                 ResultSet rs = st.executeQuery(createSubCatQuery);
                 ResultSetMetaData metaData = rs.getMetaData();
                 int count=1;
                 jPanelSubCategory.removeAll();
                 jCheckBoxSubCategory = new JCheckBox[500];
                
                 
                 while(rs.next()){
                     jCheckBoxSubCategory[count] = new JCheckBox(rs.getString(1));
                     jPanelSubCategory.add(jCheckBoxSubCategory[count]);
                     //jScrollPaneBusCategory.setViewportView(jPanelBusCategory);
                     jCheckBoxSubCategory[count].setBounds(20,20*count,100*count,500 );
                     //jCheckBoxSubCategory[count].setVisible(true);
                     count++;
                 }
                 pack();
                 subCatSelected = new String[count-1];
                         
                 rs.close();
                 st.close();
            dbConnect.closeConnection(con);
            }catch (SQLException ex) {
                Logger.getLogger(Hw3.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(Hw3.class.getName()).log(Level.SEVERE, null, ex);
            }
        //JOptionPane.showMessageDialog(new JFrame(),createSubCatQuery);
        //JOptionPane.showMessageDialog(new JFrame(),createSubCatQuery);
    }
    private void populateBusCategory(){
        populate populate = new populate();
        int num = populate.getBusCategories().length;
       // jScrollPaneBusCategory.add(jPanelBusCategory);
        jCheckBoxBusCategory = new JCheckBox[num];
        for(int i=0;i<jCheckBoxBusCategory.length;i++){
           jCheckBoxBusCategory[i] = new JCheckBox(populate.getBusCategories()[i]);
           jPanelBusCategory.add(jCheckBoxBusCategory[i]);
           //jScrollPaneBusCategory.setViewportView(jPanelBusCategory);
           jCheckBoxBusCategory[i].setBounds(20,20*(i+1),100*(i+1),50 );
           
           //jCheckBoxBusCategory[i].addItemListener(null);
        }
        pack();
    }
    
    /*public void itemStateChanged(ItemEvent e) {
        String[] busCatSelected = null;
        boolean isChcked = false;
        int count = 0;
        for(int i=0;i<jCheckBoxBusCategory.length;i++){
            if(jCheckBoxBusCategory[i].isSelected()){
               busCatSelected[count] = jCheckBoxBusCategory[i].getText();
               count++;
            }  
        }
        JOptionPane.showMessageDialog(new JFrame(),count);
        
    }*/
    private String createUserQuery(){
        String createUser = null;
        int revCountValue = 0;
        String revCountCondition = ">";
        int noOfFriendsValue = 0;
        String friendsCondition = ">";
        int avgStarsValue = 0;
        String avgStarsCondition = ">";
        String selectCondition = "OR";
      
        if((jTextFieldReviewCountValue.getText()!=null) && (jComboBoxReviewCount.getSelectedIndex()>0)){
         revCountValue=Integer.parseInt(jTextFieldReviewCountValue.getText());
         revCountCondition=jComboBoxReviewCount.getSelectedItem().toString();
        }
        if((jTextFieldNoOfFriendsValue.getText()!=null) && (jComboBoxFriends.getSelectedIndex()>0) ){
         noOfFriendsValue=Integer.parseInt(jTextFieldNoOfFriendsValue.getText());
         friendsCondition=jComboBoxFriends.getSelectedItem().toString();
        }
        if((jTextFieldAvgStarsValue.getText()!=null) && (jComboBoxAvgStars.getSelectedIndex()>0)){
         avgStarsValue=Integer.parseInt(jTextFieldAvgStarsValue.getText());
         avgStarsCondition=jComboBoxAvgStars.getSelectedItem().toString();
        }
        
        if(!("AND, OR between attributes".equals(jComboBoxSelectCondition.getSelectedItem().toString())))
            
            selectCondition = jComboBoxSelectCondition.getSelectedItem().toString();
        
        
        String memSince = (new SimpleDateFormat("YYYY-MM")).format(jDateChooserMemberSince.getDate());
        
        createUser = "SELECT name AS NAME ,yelping_since,average_stars AS STARS, user_id"
                + " FROM YELP_USER Y WHERE Y.REVIEW_COUNT" +" "
                + revCountCondition+" "+ revCountValue+" "+ selectCondition+" Y.NUMOFFRIENDS"+" "
                + friendsCondition +" "+noOfFriendsValue+" " + selectCondition+" Y.AVERAGE_STARS" +" "
                + avgStarsCondition+" " + avgStarsValue+" "+ selectCondition+" TO_DATE(Y.YELPING_SINCE, 'yyyy-mm')> TO_DATE('" 
                + memSince+ "', 'yyyy-mm')";
        return createUser;
    }
    private void displayResultTable(String selectQuery){
        //Connecting_DB dbConnect = new Connecting_DB();
        dbConnect = new Connecting_DB();
        try {
            jTextAreaQueryBuilder.setText(selectQuery);
            jTextAreaQueryBuilder.setLineWrap(true);
            //selectUser = "SELECT COUNT(*) FROM YELP_USER";
           // selectUser = "SELECT name AS NAME ,yelping_since,average_stars AS STARS, user_id FROM YELP_USER WHERE ROWNUM<=100";
            Connection con=dbConnect.openConnection();
           // jLabelQueryBuilder.setText("DbConnection Open");
           PreparedStatement pst = con.prepareStatement(selectQuery);
            ResultSet rs =  pst.executeQuery();
            DefaultTableModel displayDataTable = new DefaultTableModel();
            ResultSetMetaData metaData = rs.getMetaData();
               int columns = metaData.getColumnCount();
                String[]columnNames = new String[columns];
                for(int i=1;i<=columns;i++){
                    columnNames[i-1]= metaData.getColumnName(i);
                         
                }
                displayDataTable.setColumnIdentifiers(columnNames);
                
                //now populate the data
                while(rs.next()){
                    String[] rowData = new String[columns];
                    for(int i=1;i<=columns;i++){
                        rowData[i-1] = rs.getString(i);
                    }
                   displayDataTable.addRow(rowData);
                }
            jTable2.setModel(displayDataTable);
            jTable2.setVisible(true);
            jTable2.setFillsViewportHeight(true);
             rs.close();
            pst.close();
            dbConnect.closeConnection(con);
            
            
        } catch (SQLException ex) {
            Logger.getLogger(Hw3.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Hw3.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
        // TODO add your handling code here:
        int row = jTable2.getSelectedRow();
        int column = jTable2.getColumnCount();
        JFrame reviewFrame = new JFrame("Reviews");
        JPanel reviewPanel = new JPanel();
        JScrollPane reviewPcrollPane ;
        JTable reviewTable= new JTable();
        String id = null;
        String reviewQuery = null;
        //String display = (String)jTable2.getValueAt(row, 0) ;
            for(int i=0;i<column;i++){
                String temp = jTable2.getColumnName(i);
            if(jTable2.getColumnName(i).equalsIgnoreCase("USER_ID")){
            id = (String) jTable2.getValueAt(row,i);
            reviewQuery= "select B.NAME AS BUSINESSNAME,R.REVIEW_DATE, R.TEXT from YELP_BUSINESS B, YELP_REVIEW R\n" +
                 "where B.BUSINESS_ID=R.BUSINESS_ID AND R.USER_ID =?";
            }
            else if(jTable2.getColumnName(i).equalsIgnoreCase("BUSINESS_ID")){
                id = (String) jTable2.getValueAt(row,i);
                reviewQuery= "select U.NAME AS USERNAME,R.REVIEW_DATE, R.TEXT from YELP_USER U, YELP_REVIEW R\n" +
                 "where U.USER_ID=R.USER_ID AND R.BUSINESS_ID =?";
            }
            continue;
            }
           //Connecting_DB dbConnect = new Connecting_DB();
            dbConnect = new Connecting_DB();
            try {
                Connection con = dbConnect.openConnection();
                 PreparedStatement pst = con.prepareStatement(reviewQuery);
                 pst.setString(1, id);
                 ResultSet rs = pst.executeQuery();
                 ResultSetMetaData metaData = rs.getMetaData();
                 //int review_column = metaData.getColumnCount();
                 DefaultTableModel displayDataTable = new DefaultTableModel();
                 
                 int columns = metaData.getColumnCount();
                String[]columnNames = new String[columns];
                for(int i=1;i<=columns;i++){
                    columnNames[i-1]= metaData.getColumnName(i);
                         
                }
                displayDataTable.setColumnIdentifiers(columnNames);
                
                //now populate the data
                while(rs.next()){
                    String[] rowData = new String[columns];
                    for(int i=1;i<=columns;i++){
                        rowData[i-1] = rs.getString(i);
                    }
                   displayDataTable.addRow(rowData);
                }
            
             rs.close();
            pst.close();
            dbConnect.closeConnection(con);
                 /*String display = "Reviews: ";
                 while(rs.next()){
                     for(int j=0;j<review_column;j++){
                        display += rs.getString(j+1)+"     ";
                     }  
                 }*/
                 if(column==0)
                  JOptionPane.showMessageDialog(reviewFrame, "No Reviews ");    
                 else{
                     reviewFrame.setSize(1300, 200);
                     reviewFrame.setLocationRelativeTo(null);
                     reviewPanel.setLayout(new BorderLayout());
                     reviewFrame.getContentPane().add(reviewPanel);
                     
                    reviewTable.setModel(displayDataTable);
                     reviewTable.getColumnModel().getColumn(0).setPreferredWidth(100);
                     reviewTable.getColumnModel().getColumn(1).setPreferredWidth(3);
                     reviewTable.getColumnModel().getColumn(2).setPreferredWidth(1000);
                     reviewPcrollPane = new JScrollPane(reviewTable);
                     reviewPcrollPane.setVisible(true);
                     reviewPanel.add(reviewPcrollPane,BorderLayout.CENTER);
                     reviewFrame.setVisible(true);
                     
                     reviewTable.setVisible(true);
                     reviewTable.setFillsViewportHeight(true);
                 }
                   //JOptionPane.showMessageDialog(frame, display); 
                  //pst.close();
                 //rs.close();
                 //dbConnect.closeConnection(con);
            } catch (SQLException ex) {
            } catch (ClassNotFoundException ex) {
            }
          
                  
            
        
        
       
    }//GEN-LAST:event_jTable2MouseClicked

    private void jRadioButtonUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonUserActionPerformed

    private void jButtoCatToSubCatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtoCatToSubCatActionPerformed
        // TODO add your handling code here:
        busCatSelected = new String[28];
        boolean isChcked = false;
        int count = 0;
        for(int i=0;i<jCheckBoxBusCategory.length;i++){
            if(jCheckBoxBusCategory[i].isSelected()){
                busCatSelected[count] = jCheckBoxBusCategory[i].getText();
                count++;
            }
        }
        populateSubCategory(busCatSelected);
        //JOptionPane.showMessageDialog(new JFrame(),count);
    }//GEN-LAST:event_jButtoCatToSubCatActionPerformed

   
    public static void main(String args[]) throws SQLException, ClassNotFoundException, ParseException {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Hw3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Hw3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Hw3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Hw3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
     
       
       
       
        
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Hw3().setVisible(true);
               // jLabelQueryBuilder.setText("SELECT name,yelping_since,average_star \n FROM YELP_USER1\n WHERE");
                
            }
        });
        
    }
    
     /** 

        * Delete Data from tables before population
     * @param conn
        * @param con 

        */   

      

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button jButtoCatToSubCat;
    private javax.swing.JButton jButtonExecuteQuery;
    private javax.swing.JComboBox jComboBoxAvgStars;
    private javax.swing.JComboBox jComboBoxCheckinFrom;
    private javax.swing.JComboBox jComboBoxCheckinTo;
    private javax.swing.JComboBox jComboBoxFriends;
    private javax.swing.JComboBox jComboBoxNumOfCheckins;
    private javax.swing.JComboBox jComboBoxReviewCount;
    private javax.swing.JComboBox jComboBoxReviewStars;
    private javax.swing.JComboBox jComboBoxReviewVotes;
    private javax.swing.JComboBox jComboBoxSelectCondition;
    private com.toedter.calendar.JDateChooser jDateChooserFrom;
    private com.toedter.calendar.JDateChooser jDateChooserMemberSince;
    private com.toedter.calendar.JDateChooser jDateChooserTo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JPanel jPanelBusCategory;
    private javax.swing.JPanel jPanelSubCategory;
    private javax.swing.JPanel jPanelUser;
    private javax.swing.JRadioButton jRadioButtonBusiness;
    private javax.swing.JRadioButton jRadioButtonUser;
    private static javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextArea jTextAreaQueryBuilder;
    private javax.swing.JTextField jTextFieldAvgStarsValue;
    private javax.swing.JTextField jTextFieldCheckinValue;
    private javax.swing.JTextField jTextFieldFrmCheckin;
    private javax.swing.JTextField jTextFieldNoOfFriendsValue;
    private javax.swing.JTextField jTextFieldReviewCountValue;
    private javax.swing.JTextField jTextFieldReviewStarsValue;
    private javax.swing.JTextField jTextFieldReviewVotesValue;
    private javax.swing.JTextField jTextFieldToCheckin;
    // End of variables declaration//GEN-END:variables
 //Variable Declaration for User
 //private String selectUser;
 private String memberSince;
 private String reviewCountCond;
 private String reviewCountValue;
 private String numOfVotesCond;
 private String numOfVotesValue;
 private String averageStarsCond;
 private String averageStarsValue;
 private String selectAttributes;
 private static JCheckBox jCheckBoxBusCategory[];
 private static JCheckBox jCheckBoxSubCategory[];
 //private static JTable jTable1;
 private static Connecting_DB dbConnect;
 private static String[] busCatSelected;
 private static String[] subCatSelected;
 private static int subCatCount = 0;
         
}
